# Generated by Django 2.2.28 on 2023-01-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='salesDate',
        ),
        migrations.AddField(
            model_name='sales',
            name='itemName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
